# Collection of Data Structure Challenges (Module 2 Extras)
# Exercises generated by AI and solved by me to reinforce knowledge.
# This file covers list classification, dictionary properties, and top-ranking with tuples.

# 1. Classifying Unique vs Repeated Words
print("--- Challenge 1: Unique and Repeated ---")
wrd = list()
repeatedwrd = list()
x = "the clown ran after the car and the car ran into the tent"
line = x.split()
for words in line:
    if words not in wrd:
        wrd.append(words)
    elif words not in repeatedwrd:
        repeatedwrd.append(words)

wrd.sort()
repeatedwrd.sort()
print("Únicas: ", wrd)
print("Repetidas: ", repeatedwrd)

# 2. Dictionary of Word Lengths (Finding the longest word)
print("\n--- Challenge 2: Word Lengths ---")
diccionario = dict()
bigword = None
biglen = None
x = "python java javascript c++ ruby go scala"
words = x.split()
for word in words:
    diccionario[word] = len(word)

for key, value in diccionario.items():
    if biglen is None or value > biglen:
        biglen = value
        bigword = key
print("Longest word:", bigword, "with", biglen, "characters")

# 3. Top 3 Ranking using Tuples and Slicing
print("\n--- Challenge 3: Top 3 Items ---")
fruits = "apple banana apple orange banana apple pear orange banana"
words = fruits.split()
dic = dict()
for word in words:
    dic[word] = dic.get(word, 0) + 1

lst = list()
for key, val in dic.items():
    newtup = (val, key)
    lst.append(newtup)

lst = sorted(lst, reverse=True)
print("Top 3 Fruits:")
for v, k in lst[:3]:
    print(k, ":", v)
