# Collection of Logic Functions
# PY4E - Module 1 (Extra Practice: Exercises generated by AI and solved by me to reinforce knowledge)
# This file contains several functions I practiced to master math operations, leap years, and discounts.
# They have terms in spanish, but still understandable ( I think... :) )

# 1. Function with multiple results
def operacion(a, b):
    suma = a + b
    resta = a - b
    multiplicacion = a * b
    return suma, resta, multiplicacion

# 2. Leap year logic (using % and and/or)
def es_bisiesto(ano):
    if (ano % 4 == 0) and (ano % 100 != 0) or (ano % 400 == 0):
        return "Es bisiesto"
    else:
        return "No es bisiesto"

# 3. Discount logic
def precio_final(precio):
    if precio >= 100:
        descuento = precio * 0.10
        total = precio - descuento
        return total
    else:
        return precio

# --- Part 2: Testing my functions ---

# Testing math operations
print("--- Testing Operations ---")
s, r, m = operacion(10, 5)
print("Suma:", s)
print("Resta:", r)
print("Multiplicacion:", m)

# Testing Leap Year
print("--- Testing Year ---")
ano = 2024
resultado = es_bisiesto(ano)
print("El año", ano, resultado)

# Testing Discounts
print("--- Testing Discounts ---")
p = 120.0
pf = precio_final(p)
print("Precio original:", p, "Precio final:", pf)
